services:
  frontend:
    container_name: frontend
    image: ghcr.io/peu77/workshifts_frontend:latest
    environment:
      - VITE_API_HOST=http=//192.168.101.81:5000
    expose:
      - 4000
    ports:
      - 4000:4000
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres